python train.py \
    --log_level info \
    --model_name_or_path=meta-llama/Llama-2-7b-hf \
    --train_file=data/dataset_train.txt \
    --validation_file=data/dataset_dev.txt \
    --per_device_train_batch_size=1 \
    --per_device_eval_batch_size=1 \
    --gradient_accumulation_steps=64 \
    --do_train \
    --fp16 \
    --output_dir=Llama-2-7b-realtime-chat-v2 \
    --do_eval \
    --overwrite_output_dir \
    --seed=42 \
    --data_seed=42 \
    --eval_steps=51 \
    --logging_steps=2 \
    --save_total_limit=3 \
    --evaluation_strategy=steps \
    --lr_scheduler_type=cosine \
    --num_train_epochs=2 \
    --save_steps=51 \
    --learning_rate=2e-05 \
    --weight_decay=0.1 \
    --warmup_ratio=0.03 \
    --metric_for_best_model=eval_loss \
    --load_best_model_at_end \
    --dataloader_drop_last \
    --use_peft